#!/bin/sh
sleep 1
launchctl unload /System/Library/LaunchDaemons
ls /etc/rc.d | while read a; do /etc/rc.d/$a; done
launchctl load /System/Library/LaunchDaemons/com.apple.logd.plist
sleep 1
launchctl load /Library/LaunchDaemons
launchctl load /System/Library/LaunchDaemons

# Fetch then extract iosbinpack64.
cd /
wget http://newosxbook.com/tools/iosbinpack64.tgz
tar -xvzf iosbinpack64.tgz
rm -rf iosbinpack64.tgz

exit 0
